api/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    CommentListCreateAPIView,
    UserCommentListAPIView,
    CommentDetailDataView,
    ContentCommentsAPIView,
    CommentDeleteAPIView,
    CommentUpdateAPIView,

    TopRatedMovieListView,
    MovieDetailView,
    GenreListView
)

urlpatterns = [

    # List all comments & Create a new comment
    path('comment/', CommentListCreateAPIView.as_view()),

    # List all comments of a user
    path('comment/user/', UserCommentListAPIView.as_view()),

    # Retrieve a comment details
    path('comment/<int:pk>/', CommentDetailDataView.as_view()),

    # Get comments for a given content_id
    path('comment/content/<int:content_id>/',
         ContentCommentsAPIView.as_view()),

    # Delete a comment
    path('comment/<int:pk>/delete/', CommentDeleteAPIView.as_view()),

    # Update a comment
    path('comment/<int:pk>/update/', CommentUpdateAPIView.as_view()),



    # List all movies
    path('movie/top_rated/', TopRatedMovieListView.as_view()),

    # Movie details
    path('movie/<int:movie_id>/', MovieDetailView.as_view(), name='movie-detail'),

    # List all genres
    path('genre/', GenreListView.as_view()),
]

core/urls.py
from django.urls import include, path


from core.views import (
    Home,
    MovieDetailView,
    SignUpView,
    TvSeriesDetailView,
    GenresContentView,
    AllMovieView,
    AllSeriesView,
)

urlpatterns = [
    path("", Home.as_view(), name="home"),

    path("movie-detail/<int:movie_id>/",
         MovieDetailView.as_view(), name="movie_details"),

    path("series-detail/<int:movie_id>",
         TvSeriesDetailView.as_view(), name="series_details"),

    path("genre/<int:genre_id>/<str:genre_name>/",
         GenresContentView.as_view(), name="genre_content"),

    path("movies/", AllMovieView.as_view(), name="movies"),

    path("tv-series/", AllSeriesView.as_view(), name="series"),

    path("signup/", SignUpView.as_view(), name="signup"),
]

critiQs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


# from drf_yasg import openapi
# from drf_yasg.views import get_schema_view
from rest_framework import permissions

# schema_view = get_schema_view(
#     openapi.Info(
#         title="critiQs API",
#         default_version='v1',
#         description="API for CRUD operations for movies and comments",
#         # terms_of_service="https://www.google.com/policies/terms/",
#         contact=openapi.Contact(email="aagarw14@stevens.edu"),
#         license=openapi.License(name="BSD License"),
#     ),
#     public=True,
#     permission_classes=[permissions.AllowAny],
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/', include('api.urls')),
    path('', include('core.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),

    path('', include('django.contrib.auth.urls')),


    # path('auth/', include('accounts.urls')),

    # re_path(r'^swagger(?P<format>\.json|\.yaml)$',
    #         schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # re_path(r'^swagger/$', schema_view.with_ui('swagger',
    #                                            cache_timeout=0), name='schema-swagger-ui'),
    # re_path(r'^redoc/$', schema_view.with_ui('redoc',
    #                                          cache_timeout=0), name='schema-redoc'),
]

core/models.py
from django.db import models

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from api.models import Comment
from django.contrib.auth import get_user_model
User = get_user_model()


class CommentForm(forms.ModelForm):

    body = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'What do you think...?',
                'rows': 2,
            }
        )
    )

    class Meta:
        model = Comment
        fields = ['body', 'content_id', 'user']


class CustomUserCreationForm(UserCreationForm):

    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Username',
            }
        )
    )

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
                'autocomplete': 'new-password',
            }
        )
    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm Password',
                'autocomplete': 'new-password',
            }
        )
    )

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

core/views.py
import random
import requests
from api.models import Comment
from .forms import (
    CommentForm,
    CustomUserCreationForm,
)

from django.conf import settings
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView
)
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.contrib.auth import get_user_model
User = get_user_model()


API_KEY = settings.MOVIE_API_KEY


def request_data(url):
    try:
        try:
            response = requests.get(url,
                                    timeout=5,
                                    headers={'Content-Type': 'application/json'})
        except requests.Timeout:
            response = None
        if not response or response.status_code != 200:
            response = requests.get(url,
                                    timeout=5,
                                    headers={'Content-Type': 'application/json'})
            if response.status_code != 200:
                return None
    except (ConnectionError, requests.Timeout):
        return None

    results = response.json()

    return results


def get_movie_cast(movie_id: int):
    url = "https://api.themoviedb.org/3/movie/"+movie_id + \
        "/credits?api_key="+API_KEY+"&language=en-US"
    return request_data(url)['cast']


def get_similar_movie(movie_id: int):
    url = "https://api.themoviedb.org/3/movie/"+movie_id + \
        "/similar?api_key="+API_KEY+"&language=en-US&page=1"
    return request_data(url)['results']


def get_popular():
    url = "https://api.themoviedb.org/3/movie/popular?api_key="+API_KEY + \
        "&language=en-US&page=1&append_to_response=videos"
    return request_data(url)['results']


def get_top_rated():
    url = "https://api.themoviedb.org/3/movie/top_rated?api_key="+API_KEY + \
        "&language=en-US&page=1&append_to_response=videos"
    return request_data(url)['results']


def get_upcoming():
    url = "https://api.themoviedb.org/3/movie/upcoming?api_key="+API_KEY + \
        "&language=en-US&page=1&append_to_response=videos"
    return request_data(url)['results']


def get_trending():
    url = "https://api.themoviedb.org/3/trending/movie/day?api_key="+API_KEY
    return request_data(url)['results']


def get_latest_tv_series(page=1):
    url = "https://api.themoviedb.org/3/tv/on_the_air?api_key=" + \
        API_KEY+"&language=en-US&page="+str(page)
    results = request_data(url)['results']
    return results


def get_movie_detail(movie_id: str):
    url = "https://api.themoviedb.org/3/movie/"+str(movie_id) + \
        "?api_key="+API_KEY+"&language=en-US"
    return request_data(url)


def get_tv_series_detail(tv_id: str):
    url = "https://api.themoviedb.org/3/tv/"+str(tv_id) + \
        "?api_key="+API_KEY+"&language=en-US"
    return request_data(url)


def get_tv_series_cast(tv_id):
    url = "https://api.themoviedb.org/3/tv/"+str(tv_id) + \
        "/credits?api_key="+API_KEY+"&language=en-US"
    return request_data(url)['cast']


def get_tv_series_similar(tv_id):
    url = "https://api.themoviedb.org/3/tv/"+str(tv_id) + \
        "/similar?api_key="+API_KEY+"&language=en-US&page=1"
    return request_data(url)['results']


def get_movie_with_genre(genre_id):
    url = "https://api.themoviedb.org/3/discover/movie?api_key=" + \
        API_KEY + "&with_genres=" + str(genre_id)
    return request_data(url)['results']


def get_show_with_genre(genre_id):
    url = "https://api.themoviedb.org/3/discover/tv?api_key=" + \
        API_KEY + "&with_genres=" + str(genre_id)
    return request_data(url)['results']


def get_popular_tv_series():
    url = "https://api.themoviedb.org/3/tv/popular?api_key=" + \
        API_KEY + "&&language=en-US&page=1"
    return request_data(url)['results']


def get_top_rated_tv_series():
    url = "https://api.themoviedb.org/3/tv/top_rated?api_key=" + \
        API_KEY + "&language=en-US"
    return request_data(url)['results']


class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, *args, **kwargs):

        popular_movies = get_popular()
        kwargs['carousel'] = popular_movies[:5]
        kwargs['popular_movies'] = popular_movies[5:17]

        upcoming_movies = get_upcoming()
        kwargs['upcoming'] = upcoming_movies[:12]

        top_rated_movies = get_top_rated()
        kwargs['top_rated'] = top_rated_movies[:12]

        latest_tv_series = get_latest_tv_series()
        kwargs['latest_tv_series'] = latest_tv_series[:12]

        kwargs['genres'] = settings.GENERES
        return super().get_context_data(**kwargs)


class ContentDetailView(CreateView):
    model = Comment
    form_class = CommentForm

    def post(self, request, **kwargs):
        if request.method == 'POST':
            request.POST._mutable = True
            movie_id = self.kwargs['movie_id']
            comment = request.POST.get('body')

            request.POST['content_id'] = movie_id
            request.POST['user'] = self.request.user
            request.POST._mutable = False
            form = CommentForm()
            if form.is_valid():
                form.save()
            else:
                print(form.errors)

        return super(ContentDetailView, self).post(request, **kwargs)


class MovieDetailView(ContentDetailView):
    template_name = 'movie_detail.html'

    def get_context_data(self, *args, **kwargs):
        movie_id = str(self.kwargs['movie_id'])
        kwargs['movie'] = get_movie_detail(movie_id)

        comments = Comment.objects.filter(content_id=movie_id).order_by('-date_created')
        kwargs['comments'] = comments

        kwargs['genres'] = settings.GENERES
        kwargs['credits'] = get_movie_cast(movie_id)
        kwargs['similar'] = get_similar_movie(movie_id)[:18]

        return super().get_context_data(**kwargs)


class TvSeriesDetailView(ContentDetailView):
    template_name = 'tv_series_detail.html'

    def get_context_data(self, *args, **kwargs):
        series_id = str(self.kwargs['movie_id'])
        kwargs['series'] = get_tv_series_detail(series_id)

        comments = Comment.objects.filter(content_id=series_id)
        kwargs['comments'] = comments

        kwargs['genres'] = settings.GENERES
        kwargs['credits'] = get_tv_series_cast(series_id)
        kwargs['similar'] = get_tv_series_similar(series_id)[:18]

        return super().get_context_data(**kwargs)


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("home")
    template_name = "registration/signup.html"

    def get_context_data(self, *args, **kwargs):
        kwargs['genres'] = settings.GENERES
        return super().get_context_data(**kwargs)


class GenresContentView(TemplateView):
    template_name = "movie_results.html"

    def get_context_data(self, *args, **kwargs):
        content_id = str(self.kwargs['genre_id'])
        kwargs["content"] = get_movie_with_genre(content_id)
        kwargs["title"] = self.kwargs['genre_name']
        kwargs['genres'] = settings.GENERES
        return super().get_context_data(**kwargs)


class AllMovieView(TemplateView):
    template_name = "movie_results.html"

    def get_context_data(self, **kwargs):

        popular = get_popular()
        trending = get_trending()
        upcoming = get_upcoming()

        movie_list = popular + trending + upcoming
        # print(movie_list)
        # content = random.shuffle(movie_list)

        kwargs['content'] = movie_list
        kwargs['genres'] = settings.GENERES

        return super().get_context_data(**kwargs)


class AllSeriesView(TemplateView):
    template_name = "tv_results.html"

    def get_context_data(self, **kwargs):

        latest = get_latest_tv_series()
        top_rated = get_top_rated_tv_series()
        popular = get_popular_tv_series()

        content = latest + top_rated + popular

        kwargs['content'] = content
        kwargs['genres'] = settings.GENERES

        return super().get_context_data(**kwargs)

core/templates/movie_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}



{% block title %} - Movie Detail {% endblock %}

{% block head %}


{% endblock %}


{% block body %}

<style>
	.movie-detail-card-bg {
		background-image: url("https://image.tmdb.org/t/p/original{{movie.backdrop_path}}");
		background-size: cover;
		border: 1px solid rgba(255, 255, 255, 0.18);
		border-radius: 10px;

	}

	.movie-detail-card {
		background: rgba(0, 0, 0, 0.424);
		box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
		backdrop-filter: blur(7px);
		-webkit-backdrop-filter: blur(18px);
		border-radius: 10px;
	}

	.img-fluid {
		border-radius: 10px;
	}
</style>



<div class="container">
	<section class="my-3 body">


		<div class="movie-detail-card-bg">
			<div class="movie-detail-card">

				<div class="card-body text-light">
					<div class="row">
						<div class="col-lg-4 col-md-6 col-sm-12 mb-3 mb-md-0">
							<img src="https://image.tmdb.org/t/p/original{{movie.poster_path}}" class="img-fluid"
								alt="{{movie.title}}">
						</div>
						<div class="col-lg-8 col-md-6 col-sm-12 fs-5">
							<div class="mb-3">
								<h2>
									<a href="{{movie.homepage}}" style="text-decoration: none;"
										class="text-light">{{movie.title}}</a>
								</h2>
								<h5># {{movie.tagline}}</h5>
							</div>
							<div class="mb-3">
								{% for i in movie.genres %}
								<a href="{% url 'genre_content' i.id i.name %}" style="text-decoration: none;"
									class="badge bg-primary">{{i.name}}</a>
								{% if not forloop.last %}&nbsp;{% endif %}
								{% endfor %}
							</div>
							<div class="mb-3">
								<span>📜 Overview: </span>
								{{movie.overview}}
							</div>
							<div class="mb-3">
								{% if movie.budget %}
								<span class="">💵 Budget: USD </span>
								{{movie.budget|intcomma}}
								{% endif %}
							</div>
							<div class="mb-3">
								<span class="">🌏 Languages Available: </span>
								{% for i in movie.spoken_languages %}
								{{i.english_name}}
								{% if not forloop.last %}, {% endif %}
								{% endfor %}
							</div>
							<div class="mb-3">
								<span class="">📆 Date Released: </span>
								{{movie.release_date}}
							</div>
							<div class="mb-3">
								<span class="">⌚ Running Time: </span>
								{{movie.runtime}} mins
							</div>
							<div>
								<span class="">⭐ Vote Average: </span>
								{{movie.vote_average}}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>



	<section class="my-5">

		<div class="col-12">
			<h2 class="display-4 mb-2">Beloved Cast</h2>
		</div>

		<div class="container">
			<div class="row card">
				<div class="list-group list-group-flush list-group-horizontal position-relative overflow-auto">
					{% for cast in credits %}
					<div class="list-group-item">
						<div class="card" style="width: 12rem;">
							{% if cast.profile_path %}
							<div class="">
								<img src=https://image.tmdb.org/t/p/w500{{cast.profile_path}} class="card-img-top"
									alt="{{cast.name}} original image" style="object-fit: cover; height:300px;">
							</div>
							{% else %}
							<div class="">
								<img src=https://www.shutterstock.com/image-vector/male-default-placeholder-avatar-profile-260nw-387516193.jpg
									class="card-img-top " alt="{{cast.name}} original image"
									style="height: 300px ; object-fit: cover;">
							</div>
							{% endif %}
							<div class="py-1 text-center">
								<div class="fs-b">{{cast.character}}</div>
								<div class="text-muted">{{cast.name}}</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</section>


	<div class=" mb-3">
		<section class="my-1">

			<div class="row">
				<div class="col-12">
					<h2 class="display-4 mb-2">Similar Movies</h2>
				</div>
			</div>

			<div class="row row-cols-2 row-cols-md-4 row-cols-lg-6 g-4 justify-content-center">
				{% for item in similar %}
				<div class="col mb-2">
					<!-- Movie Card -->
					<div class="card h-100 border-0">
						<a href="{% url 'movie_details' item.id %}">
							<div class="position-relative">
								{% if item.poster_path %}
								<img src="https://image.tmdb.org/t/p/w500{{item.poster_path}}"
									class="card-img-top rounded-3 shadow" alt="{{item.name}}"
									style="height: 300px; object-fit: cover;" />
								{% else %}
								<img src="{% static 'imgs/no-poster.png' %}" class="card-img-top rounded-3 shadow"
									alt="{{item.name}}" style="height: 300px; object-fit: cover;" />
								{% endif %}
								<div class="position-absolute top-0 end-0 m-2">
									<span class="badge badge-custom">
										<i class="bi bi-star-fill"></i>
										{{ item.vote_average }}
									</span>
								</div>
								<div class="tooltip-body d-none">
									<div>
										<div>
											<div class="">
												<h6>Movie Name : {{item.title}}</h6>
											</div>
											<div>
												<span class="">
													<h6>Release Date : 🕔
														{{item.release_date}}
													</h6>
												</span>
												{%if item.adult%}
												<span class="badge bg-warning text-dark rounded-pill">+18 </span>
												{%endif%}
											</div>
											<div class="">
												<h6> Average Rating: {{item.vote_average}}</h6>
											</div>
											<div class="">
												<h6> Genres: {% for i in item.genres %}
													{{i.name}}
													{% endfor %}
												</h6>

											</div>
											<div class="">
												<h6> Duration : {{item.runtime}}</h6>
											</div>
										</div>
										<div class="">
											<p class="text-light">
												</h6>overview : {{item.overview|truncatewords:20}}</>
											</p>
										</div>
									</div>
								</div>
							</div>
						</a>
					</div>
					<!-- Movie Card -->

				</div>
				{% endfor %}
			</div>
		</section>



		<section class="trending-card my-4 p-4">
			<h2>Comments ({{ comments | length }})</h2>

			{% if user.is_authenticated %}
			<ul class="list-group list-group-flush img-fluid">
				<li class="list-group-item align-items-start">
					<div class="ms-2 me-auto">
						<div class="fw-bold">
							<form action="" method="POST">
								{% csrf_token %}
								<span>
									<span class="fw-bold my-1">Commenting as @{{user.username|capfirst}}</span>
									<textarea name="body" rows="2" class="form-control"
										placeholder="What do you think...?" required id="id_body"></textarea>
									<div class="my-1 justify-content-center">
										<button type="submit" class="btn btn-primary btn-sm">Post</button>
									</div>

								</span>
							</form>
						</div>
					</div>
				</li>
				{% else %}
				<div>
					<a href="{% url 'login' %}" class="btn btn-primary">Login to Comment</a>
				</div>
				{% endif %}


				{% for comment in comments %}
				<li class="list-group-item d-flex justify-content-between align-items-start">
					<div class="ms-2 me-auto">
						<div class="fw-bold">
							<span>
								<img width="30" height="30"
									src="https://img.icons8.com/external-kiranshastry-gradient-kiranshastry/64/external-user-interface-kiranshastry-gradient-kiranshastry.png"
									alt="external-user-interface-kiranshastry-gradient-kiranshastry" />
							</span>
							<span>
								{{ comment.user.username | capfirst }}
							</span>
						</div>
						<div>
							{{ comment.body }}
						</div>
					</div>
					<span class="badge bg-primary rounded-pill">{{ comment.date_created | naturaltime }}</span>
				</li>
				{% endfor %}
			</ul>
		</section>


	</div>
</div>



{% endblock %}

core/templates/movie_results.html
{% extends 'base.html' %} {% load static %}{% load humanize %}

{% block title %}
{% if title %}
{{ title }}
{% else %}
Movies
{% endif %} {% endblock %}

{% block head %} {% endblock %}





{% block body %}

<div class="container mb-3">

	<section class="my-1">

		<div class="row">
			<div class="col-12">
				<h2 class="display-4 mb-2">

					{% if title %}
					{{ title }}
					{% else %}
					Movies
					{% endif %}
				</h2>
			</div>
		</div>

		<div class="row row-cols-2 row-cols-md-4 row-cols-lg-6 g-4 justify-content-center">
			{% for item in content %}
			<div class="col mb-2">
				<!-- Movie Card -->
				<div class="card h-100 border-0">
					<a href="{% url 'movie_details' item.id %}">
						<div class="position-relative">
							<img src="https://image.tmdb.org/t/p/w500{{item.poster_path}}"
								class="card-img-top rounded-3 shadow" alt="{{item.name}} original image"
								style="height: 300px; object-fit: cover;" />
							<div class="position-absolute top-0 end-0 m-2">
								<span class="badge badge-custom">
									<i class="bi bi-star-fill"></i>
									{{ item.vote_average }}
								</span>
							</div>
							<div class="tooltip-body d-none">
								<div>
									<div>
										<div class="">
											<h6>Movie Name : {{item.title}}</h6>
										</div>
										<div>
											<span class="">
												<h6>Release Date : 🕔
													{{item.release_date}}
												</h6>
											</span>
											{%if item.adult%}
											<span class="badge bg-warning text-dark rounded-pill">+18 </span>
											{%endif%}
										</div>
										<div class="">
											<h6> Average Rating: {{item.vote_average}}</h6>
										</div>
										<div class="">
											<h6> Genere: {{movie.genres}}{{.name}}</h6>
										</div>
										<div class="">
											<h6> Duration : {{movie.runtime}}</h6>
										</div>
									</div>
									<div class="">
										<p class="text-light">
											</h6>overview : {{item.overview|truncatewords:20}}</>
										</p>
									</div>
								</div>
							</div>
						</div>
					</a>
				</div>
				<!-- Movie Card -->

			</div>
			{% endfor %}
		</div>

	</section>
</div>





{% endblock %}


{% block js %}


{% endblock%}

core/templates/tv_results.html
{% extends 'base.html' %} {% load static %}{% load humanize %}

{% block title %}
{% if title %}
{{ title }}
{% else %}
TV Shows
{% endif %} {% endblock %}

{% block head %} {% endblock %}





{% block body %}

<div class="container mb-3">

	<section class="my-1">

		<div class="row">
			<div class="col-12">
				<h2 class="display-4 mb-2">
					{% if title %}
					{{ title }}
					{% else %}
					Series
					{% endif %}
				</h2>
			</div>
		</div>
		<!-- <div class="px-4 pb-4"> -->

		<div class="row row-cols-2 row-cols-md-4 row-cols-lg-6 g-4 justify-content-center">
			{% for item in content %}
			<div class="col mb-2">
				<div class="card h-100 border-0">
					<a href="{% url 'series_details' item.id %}">
						<div class="position-relative">
							<img src="https://image.tmdb.org/t/p/w500{{item.poster_path}}"
								class="card-img-top rounded-3 shadow" alt="{{item.name}} original image"
								style="height: 300px; object-fit: cover;" />
							<div class="position-absolute top-0 end-0 m-2">
								<span class="badge badge-custom">
									<i class="bi bi-star-fill"></i>
									{{ item.vote_average }}
								</span>
							</div>
							<div class="tooltip-body d-none">
								<div>
									<div>
										<div class="">
											<h6>Name : {{item.name}}</h6>
										</div>
										<div>
											<span class="">
												<h6>Release Date : 🕔
													{{item.first_air_date}}
												</h6>
											</span>
											{%if item.adult%}
											<span class="badge bg-warning text-dark rounded-pill">+18 </span>
											{%endif%}
										</div>
										<div class="">
											<h6> Average Rating: {{item.vote_average}}</h6>
										</div>
										<div class="">
											<h6> Genres: {% for i in item.genres %}
												{{i.name}}
												{% endfor %}
											</h6>

										</div>
										<div class="">
											<h6> Duration : {{item.runtime}}</h6>
										</div>
									</div>
									<div class="">
										<p class="text-light">
											</h6>Overview : {{item.overview|truncatewords:20}}</>
										</p>
									</div>
								</div>
							</div>
						</div>
					</a>
				</div>

			</div>
			{% endfor %}
		</div>
		<!-- </div> -->

	</section>



</div>





{% endblock %}


{% block js %}


{% endblock%}